### ISSUE TITLE
The content of the resource server can still be requested and obtained after the accessToken expires

### ISSUE THREAD

**Issue by meimosor** [Basit-Mahmood/spring-authorization-server-spring-boot-3#5] opened 2023-04-28 12:38 UTC
When the client's accessToken Time is set to 1 minute, after logging in, the accessToken can still obtain data from the resource server after more than one minute, rather than returning 401

**Comment by Basit-Mahmood** [comment] 2023-05-06 08:52
@meimosor If no steps provided that how can I reproduce it or what you tried. It is really hard to answer the question. 

Anyways following is what I did try.

1) In SpringAuthorizationServer project. In the file **oauth2-client-test-data.sql**. I changed for the password-client-id, **"access_token_time**" to **"1"** and **"access_token_time_unit**" to **"minute"**. This is for table **oauth2_client_token_setting**

2) In SpringAuthorizationServer project. In the file **oauth2-client-test-data.sql**. For password-client-id,  the "**authorization_grant_type**" is "**password,refresh_token**". This is for table **oauth2_client**

3) I started all three projects i.e, **SpringAuthorizationServer**, **SpringResourceServer** and **SpringOAuthClient**

4) I opened the URL http://127.0.0.1:8080/springauthserverclient in the browser

5) Login with user1 and password

6) Click on the Password link.

7) The response came back

8) I opened the URL http://127.0.0.1:9000/springauthserver/h2-console in the browser

9) Type password in the Password filed and login to H2

10) Executed the query `select * from oauth2_authorization`; and I can see that the access token time is 1 minute. But for refresh token it is 1 day.

11) I let 2 minute passed.

12) I again clicked on the Password link

Remember you are using **SpringOAuthClient**. If exception is throws from SpringAuthorizationServer then it automatically calls for RefreshToken. There is a class **RefreshTokenOAuth2AuthorizedClientProvider.java**. This class calls the SpringAuthorizationServer for Refresh Token with the required request. 

Now in **OAuth2RefreshTokenAuthenticationProvider** it generates new access token and refresh token based on the refresh token access time. Here is the  code snippet of that class

	```
    OAuth2Authorization authorization = this.authorizationService.findByToken(
				refreshTokenAuthentication.getRefreshToken(), OAuth2TokenType.REFRESH_TOKEN);
    ....
         
	OAuth2Authorization.Token<OAuth2RefreshToken> refreshToken = authorization.getRefreshToken();
		if (!refreshToken.isActive()) {
			// As per https://tools.ietf.org/html/rfc6749#section-5.2
			// invalid_grant: The provided authorization grant (e.g., authorization code,
			// resource owner credentials) or refresh token is invalid, expired, revoked [...].
			throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_GRANT);
		}
	....
	// ----- Access token -----
    .....
	// ----- Refresh token -----
	OAuth2RefreshToken currentRefreshToken = refreshToken.getToken();
	if (!registeredClient.getTokenSettings().isReuseRefreshTokens()) {
		....
	}
	....
    ```
	
So I think you are doing it just like as I did. 

If you use post man to access the resource using the expire token. You should definitely get an error

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment] 2023-09-15 16:49
No comment is provided since long time. Closing the issue

**Closed as completed by Basit-Mahmood** 2023-09-15 16:49 UTC
